# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: execution.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'execution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xecution.proto\x12\x0fucser.execution\"\xb5\x01\n\x0e\x43ommandRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\x12>\n\x08\x65nv_vars\x18\x04 \x03(\x0b\x32,.ucser.execution.CommandRequest.EnvVarsEntry\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Z\n\x0f\x43ommandResponse\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x11\n\texit_code\x18\x02 \x01(\x05\x12\x0e\n\x06stdout\x18\x03 \x01(\t\x12\x0e\n\x06stderr\x18\x04 \x01(\t\"t\n\rCommandOutput\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x16\n\x0cstdout_chunk\x18\x02 \x01(\tH\x00\x12\x16\n\x0cstderr_chunk\x18\x03 \x01(\tH\x00\x12\x13\n\texit_code\x18\x04 \x01(\x05H\x00\x42\x08\n\x06output2\xbc\x01\n\x10\x45xecutionAdapter\x12T\n\x0f\x44ispatchCommand\x12\x1f.ucser.execution.CommandRequest\x1a .ucser.execution.CommandResponse\x12R\n\rStreamCommand\x12\x1f.ucser.execution.CommandRequest\x1a\x1e.ucser.execution.CommandOutput0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST_ENVVARSENTRY']._loaded_options = None
  _globals['_COMMANDREQUEST_ENVVARSENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDREQUEST']._serialized_start=37
  _globals['_COMMANDREQUEST']._serialized_end=218
  _globals['_COMMANDREQUEST_ENVVARSENTRY']._serialized_start=172
  _globals['_COMMANDREQUEST_ENVVARSENTRY']._serialized_end=218
  _globals['_COMMANDRESPONSE']._serialized_start=220
  _globals['_COMMANDRESPONSE']._serialized_end=310
  _globals['_COMMANDOUTPUT']._serialized_start=312
  _globals['_COMMANDOUTPUT']._serialized_end=428
  _globals['_EXECUTIONADAPTER']._serialized_start=431
  _globals['_EXECUTIONADAPTER']._serialized_end=619
# @@protoc_insertion_point(module_scope)
